### ISSUE TITLE
Getting Up to Speed and Helping with the Project

### ISSUE THREAD

**Issue by codesplode** [orangy/squash#11]
Hi there,

First off, thanks for starting an awesome project. I'm submitting this issue mainly because I didn't know a better way to contact you about this, but I would like to get up to speed on squash and the direction so I can help out.

I'm looking for a good SQL DSL to use for a platform my team and I are building and this looks promising, so I'm hoping to use and expand upon it in ways that everyone could benefit from.

### What I've Done

- I've forked and checked out the code
- Gone through the maven build and gotten all tests completing successfully (thank you for the thorough tests by the way)
- Updated the project to kotlin version to 1.2.71 (no code changes required)
- Confirmed the tests work
- I'm starting to clear up some of the deprecation warnings as well (mainly around reflection getting the constructors of classes)

### What I Could Use
Perhaps setting up the milestones or issues you would like to accomplish next in Github so I (and others of course) could support where it makes sense, but also know what's missing and the priorities of each item. If you wouldn't mind providing a little background, I'm happy to help with this, but am currently afraid that I won't know when something is incomplete or missing until one of my team bumps into it.

Thank you again and I look forward to helping out!

**Comment by orangy** [comment]
Hi Mike! Thanks for your interest in the project. Right now it is a little bit on hold because everyone including myself is busy with Kotlin 1.3 and all the related work. We just returned from the KotlinConf'18 :) 

Best way to discuss things is to join our Slack community (http://slack.kotlinlang.org) and then #squash channel there. 

Our plans currently are mostly making it all asynchronous through coroutines, and custom-made MySQL & PostgreSQL drivers. This is going to happen in a month or so. Hopefully. From there, we will see how it works (through Techempower Benchmarks and our own use), and decide where we want to go. Ah, also integrate kotlinx.serialization to read data from rows into data classes instead of ByteBuddy code generation. 

We don't have a lot of users here, so if you could outline your requirements, we can work from it.

**Comment by codesplode** [comment]
That's awesome. I've signed up for the Slack channel (just waiting for approval).

Love the plans going forward and depending on time, may even be willing to chip in if your team wants / needs it. We are very familiar with several database servers, jdbc, and SQL in particular which is why we end up making custom frameworks for SQL generation and such. We are very picky about performance requirements of the database layer and ration our query time / execution plan costs as we build our applications. We haven't dug much into code on jdbc drivers themselves aside from learning the parameters well to carefully tune them and writing proxies to monitor queries, etc. For this reason, I've gone through the code of MySQL's jdbc driver quite a bit in particular.

Originally, I was looking to use squash for the SQL DSL to make our queries type safe and simplify some work we are doing, but I'm certainly interested in the bigger picture you are laying out and love that the Jetbrains team recognizes the importance of it.

### Before I List My Requirements
Having worked on open source projects before, I want to be respectful and make it clear that I do not expect this project to agree with or desire to build any or all of my requirements. I am grateful for the open source code you and others produce, and will pitch in to serve our purposes and even others' if I have room, but will fork our own copy for modifications that you don't want or serve our specific needs differently. Just don't want you to feel like you are getting hammered with requirements that you have no reason or desire to build haha.

With that said, these are high-level overview of my requirements (prioritized as best I can haha):
### Thorough DSL
Mainly for SQL Standard and key database specific functions (aggregates, conditional functions, etc.), but we do not use anything too crazy beyond IFNULL, GROUP_CONCAT, LAST_INSERT_ID(). We try to stay as database in-specific as possible and focus on simple, predictable execution plan queries with good indexes backing them so supporting every database feature in isn't vital to us.

### Easy Configuration and Avoidance of Ad Hoc Connections / Queries
As easy as we can make it to configure datasources and connection pools so the developer (user in this case) doesn't have to think much about making a query and security is considered. As an example, if one of my team doesn't parameterize a query, it is their last day working with us, which luckily we've never had to act on, but why we also make it simple to avoid that issue :-) We do not use any large ORM frameworks as the overhead and SQL is usually too costly, not to mention the amount of knowledge they require for the lack of control trade off.

### Flexible ResultSet Manipulation and Conversion
This matches your serialization requirement, but I would also add some conveniences that we look at from the ResultSet perspective.
- Ability to do simple joins of two or more result sets with Kotlin
- Ability to alias items after the fact with Kotlin
- Ability to filter result sets quickly in Kotlin
- Simple API to convert results into other objects or formats

I know that's long winded, but I don't often jump into OS projects publicly because I don't like the drama and identity games people bring with the typical ones as they grow haha; hence my careful entry into this one and giving you my full perspective. I'm here to build awesome things, which I love doing, especially with others that feel the same. Please let me know how I can help and, meanwhile, I'll try to get into the code enough to make it usable in our tools so we have even more reason to help push it forward.

Thanks again for all your work, especially for Kotlin. I'd high five your whole team till my hand was soar if I could haha.

Cheers,
Mike

**Comment by orangy** [comment]
Thanks for detailed explanation, all is good :) I have no problems with forking, but I'd rather set up an environment where we can improve the code from both sides. Kotlin generally provides good means of extensibility through extension functions, so if used well, some very niche features can live in your code, while mainstream functionality can be contributed and shared. 

DSL: That's an easy part. Whatever is standard SQL should be in core lib. Anything that is not, but can be emulated with any mainstream database should be in the DSL, and implemented in the Dialect. You'll see some examples, like with ordering nulls-first, etc. Whatever is database specific (e.g. Postgress Geo extensions) goes into that module, so if you someone wants to use them, they can. 

ORM: There is no ORM, but check [Exposed](https://github.com/JetBrains/Exposed) if you need one. Exposed is where squash comes from, and it is much more maintained at this point, but has some issues (to my taste, YMMV). I prefer "graph fetching" mechanism, where the engine can help you with complex queries, but then you get just domain objects and no persistent state which is hard to maintain. However, graph API is very rough right now, needs some API design love, serialization support, etc. 

In-memory manipulation: After you read the dataset from DB response, you can get it into a `List`, or `Set`, and do whatever you need with it. Obviously, JSON serialization should be there out of the box, but isn't yet. However, I wouldn't just steam DB response to JSON for the sake of security. I think it should be following MVVM or something like this. Define your domain classes, populate them from DB query, serialize to JSON and that's it. Ideally, async all the way.

Drama: Well, while some opensource projects indeed go into too much ego and drama, quite often when they have users, they need to make careful decisions on changes. Especially opinionated changes, when it's about doing it "right". You know, "right" might be different for different people :) But I normally explain my decisions, so don't see a problem here.

**Comment by codesplode** [comment]
Thanks for the thorough response and your viewpoints.

Forking: To be clear, we usually keep our forks private so we don't distract from supporting a main project. And usually on do it when we need a feature the main project doesn't want (totally understandable). The goal being to keep the fork as compatible with the original project as possible so we can continue to contribute. Also love the extension functions 👍 

DSL: The DSL implementation is what drew me to look deeper at squash as I liked the simplicity and way you broke apart the problem, not to mention the clean separation of modules in the project. I saw some TODOs in your text file, but also noticed that some appear to be done in master so wanted to see what needed filling out or finishing.

ORM: Currently we are playing with jOOQ Generator, generating code using Pebble templating engine, that do queries using HikariCP. Kind of a roundabout way of avoiding dealing with DB metadata directly, but we've implemented field level security in these and are looking at Security views (ie: matching a user's role to the data that can be seen / manipulated). We like a very simple model (similar to the Active Record pattern), but constantly look at all the ORMs (including Exposed) and carefully choose how we want to interact. Things you mentioned like coroutine functionality and drivers are very interesting, and could replace HikariCP, but would need to be homeruns in terms of stability and performance before we could use it, which is the only reason I'm not going crazy for it now (that's a lot of weight on whoever has to build it and admirable of you to take it on in this project).

In-Memory Manipulation: Another thing that drew me in...I'm very familiar with JSON serialization via Jackson and would be all about helping with that if you like. I simply listed some examples on that end, but typically we would just want the ability to do easy conversion knowing our objects would likely be very different than what others want. Typically, we would go ResultSet -> Array of Beans/Value Objects -> JSON for serialization. As the project supports a full ORM type support, I would just request that users be able to swap the objects being converted to so the framework can always be unopinionated at its core, with opinions made in nicely drop-in functionality.

Drama: Amen to that, pragmatic decision making and trying to figure out what "right" and "elegant" really mean are core to our profession. But sometimes, with great popularity, comes great social issues and public work on an open source project often means handling folks' emotional outbursts and peer counseling, which is what usually keeps me out of the mix haha. I try very hard to invoke others' criticism, as long as it is positive, usually by saying "Tell me why this is a horrible idea..." before sharing something :-) Totally get where you are coming from and appreciate your perspective.

With that in mind, how would you like me to proceed in terms of going through the code? If I can learn it enough, I want to make some progress while the team there is focused on Kotlin itself. If you set the process, I will follow it as far as sending code, pull requests, or what help you would like.

Cheers,
Mike

**Comment by orangy** [comment]
As I said, I can't pay a lot of attention to it before we release Kotlin 1.3, unfortunately. But I'll try my best. I would suggest starting with tests. If you could contribute tests that emulate some of your typical scenarios, that would:
* verify core things work for you, and if not, we know what to fix
* help you get familiar with the API and see if it's comfortable for you, and if not, we can discuss 
* help us have more use-cases covered, so we can feel safer changing things

**Comment by codesplode** [comment]
Understood, thanks!
