### ISSUE TITLE
Refactoring FunctionExpression in BaseDialect

### ISSUE THREAD

**Issue by codesplode** [orangy/squash#23]
I have added a bunch of functions to the MySQL dialect and many would apply to the BaseDialect as well.

Currently, the base [FunctionExpression.kt](https://github.com/orangy/squash/blob/master/squash-core/src/org/jetbrains/squash/expressions/FunctionExpression.kt) implements function expressions as `interfaces` rather than a sealed class.

## Question 1
Would you be against this being refactored this as a sealed class instead of a normal interface? 

## Question 2
Would you be for or against having a `GeneralFunctionExpression` or `SimpleFunctionExpression` or `{insert your term here}` class that generalizes the function name and argument expression list for a lot of the common functions?

The benefit of this would be that [the when statement here](https://github.com/orangy/squash/blob/dc025481b7104a5e234d6df370d715b6b37c81eb/squash-core/src/org/jetbrains/squash/dialect/BaseSQLDialect.kt#L144) would become much simpler in that you could have all the special functions in the clause, then a single `is GeneralFunctionExpression -> ...` clause for all other simple functions. This would also make dialects that need a lot of custom functions much easier to implement (postgres and mysql in particular).

I have already done much of this, but I would like to share it with the project in a way that fits the projects standards, and I am interested to learn from it as well.

**Comment by orangy** [comment]
Apologies for slow reply, I'm currently busy with some other work. I have it in todo list for this week :)

**Comment by codesplode** [comment]
All good @orangy 

Just glad we are finally putting some code into the project as well, which is why we closed this issue and submitted the pull requests. If these go well and we learn how you want changes submitted to the project, we will continue with more where we can.
